apiVersion: v1
kind: Namespace
metadata:
  name: auth-tls
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-robot
  namespace: auth-tls
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: health-robot-cluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
  - kind: ServiceAccount
    name: health-robot
    namespace: auth-tls

